[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "80f6a874db12de09aa2f9466a0fecbe9f4fed61f"
os = "macos"

    [[Netpbm.download]]
    sha256 = "6b33bac8de113385e991b7340245fa675288c2b45c7db031427c46a8ce9f888f"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "2f6f810b52e01dae860070ccfd17f24976415976"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "08433e12086c32dc8b593f715e20b40abf134d87776629d85020667b5ca94f5c"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "0541c66806d3c5e6c0ec1f68a3df9e0b8b4e7471"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "f03c012ffc68ea0a9d79e241b83707746a42e90dcf46e7e71f5e52ccda60b953"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "76ea4c6de851519a134843f67f70acee69743a94"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "abe4a46a8dc0c43cd7fb1ba138a2568466ee26eac964ee65b215981d89e1ae4b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.aarch64-unknown-freebsd.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "45a1da6424a74d7911fd4a376514147ead0c67cb"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "ce7b44c468000995c15ba4eb522fba0bd76e56329d9d4b656e674749dc2f4abe"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f8cc74c367e6bec8884f787992bad5114059f57c"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "50ef346c85f49ac718a05cfcefe92c0fd0e3457a0ec00be0491b113b1a5c1c48"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0bc9be250646ae8f076af6589497c7829864776"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "fa66f2c3e62eb38e5ee63bd8b7743f49f07fc2c96f08d946687358600eeba0d2"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2e3d1ad706b61c53636bd64e969d2353599e288"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "c4e87f979428187a9bc2f0abdfc78d1db94b2379fe5ef4d3074749c6d3e5be2b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "d0a3c27bc29c9f6af63de246c07eebdd99d9fd86"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "5f0447ce18ecc5ac8850ed0ff0901293ca5ec74092c3077eb6756628c42df6c7"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "092ff910ff72b43ca3192850c8f5340635b21834"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "3682fdff4f545fa09266880bec0bc5979c8e94ab5b8f34a1d00c3c83496da96e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "50d805360657a92834e31cf4360f549ef9400705"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "92fbf089636fa939f7114733f5e7e79bfefcba0cc83730f9354f1acc7c664c72"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "riscv64"
git-tree-sha1 = "053c4bebe428225ecec87d8226f18ebeccdbdb0f"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "3b34c15f35529a5a7a32677d9e6967a1e965707de0372492bf23639b59f38a76"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.riscv64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "c7fa99a26c7604d96ad382070e9973c10efdc293"
os = "macos"

    [[Netpbm.download]]
    sha256 = "0b06cc39a9194eb99d4c7078ee691e0617de59f1c80ec593dbf437b409c32c84"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "c46cc8855fa39603b401cb3f3a3422a3ed7aee96"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "97e65388f62241c7fb8e153d32cc311c60873ca2e1354e880ba221c35c2e7325"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "f9b82d320b909bcf9347fbcc914f8f45879e3ff7"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "2f1ea1bdc5801ff5f46568b50e18022b5593fb0985e68adb0ebf19713f572e0a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "a0681398e8f4c719622335abc2b51deff40c2ea4"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "828946891b8eb81565299c6b8e143a94e8b26b9b9c985c2b0514c37f90146616"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.47+0/Netpbm.v10.86.47.x86_64-unknown-freebsd.tar.gz"
