[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "055a7754481a40a491d5156d97d7e43b8ccaeb8b"
os = "macos"

    [[Netpbm.download]]
    sha256 = "ed47d6e8cfd64eb9589f88ec85f460408b16a79c7348e41e3416f2a79fb9ad0b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "df99862696022f6d8e3d5a105bcbeec0aead55bd"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "f4754897385c09b259bd5f4212dcfd81f66254b633094cc09790932ca58b295a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "cfea00292fac2053576c6b65b634a26ad25a37f6"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d6e67da28e99b1ba3d0a061879d01d9039fe3345d591e45cbcafe51be167b813"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "4821a8733883181bc016531ffe7ed33db3eb153c"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "b9995945be118c54a12e1df6631fc1aea8664a8451dd2f34f27737f68360d56b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.aarch64-unknown-freebsd.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d53aba848095adb31c57d31e21c29e3cd8ae1eb7"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "15ec38cce4388ea788d74b5aa12fc33100c0fb6073a5079812d9b1b869976ae9"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "06a81c16ed737b6f2c311ddd16c5bcb881d822a8"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "01a5cec096fb5dab42d7e016ffea98f926bdd55ea92f723a10724923104e42d4"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fffa119907250a06d79f5603a0ec26a2a1dca446"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "448c70a3a783744bea3d2ba5ddf7d4c64d672e3266c2ab909a53508b03ee881e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8f8655cc6f1cd8a679fd042e0391dd8caac56d2"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "019f5933ae3aaa1c434d3d8f558a4430f074454c351403df82e192116dcaef5f"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "782117836e1430213236e36ed8c65b5a0321af99"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "6a4f678c07d13d8866495ea31e20452b42766cf77b25bdf43decc26788a83256"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "9655f2f6c4e34da180e51bb4dd975c0edf2ed860"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "09a36f8e6277f4accd4df90a64e4a497797ce7927de3fe95a4e8eebe4c1abc69"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "9f09219649d48049d22a4cecebb5f5cf456b65fb"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "dc5b68c7d8198a18371ca90312b2afeff90d1c09127fb326a8ac332e1384ec83"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "riscv64"
git-tree-sha1 = "d41236166f015d096c573e5b8014446b1ee1e655"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "64ce0cb75f3f86f57a5873eab2ccf9b9c83288768434b3daa7401ce082a03101"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.riscv64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "ff9d1fd630d79cd37e350cf612381b97d067d9ce"
os = "macos"

    [[Netpbm.download]]
    sha256 = "d95e0d193e17da0c109752bfea9bc23c3eb7b3548c87ef4f4b9e97754335d332"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "bb109998fc896b66677c24da83c54ad7e12a6149"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "a4dc839bc0cffbcb7306cc3ba4ec3725412a2d6d3aa59e12ee19f3f5954daa0d"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "bee9da12f9f3c8547004c40a3fb93c0e32341e47"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "c77bf40a0a37a8a34770d0b51a5c1e10c4e1fa8d39d47447e6d243e786a65f63"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "07f5b82629f8aacafbe57e1a1ff141925f31fc96"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "ab4af62b021a8971b3df0b9492478492f43dea0dee4462efc3fea8cc2a02511a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.49+0/Netpbm.v10.86.49.x86_64-unknown-freebsd.tar.gz"
