[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "ced5bb1c645887375e572df39d632723f800dbc5"
os = "macos"

    [[Netpbm.download]]
    sha256 = "23e5ad5ec9930a35fa460b0ac2f03bcadbb357247d8d4f8e4a240efb6a0cfd3e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "6bda94fa7dd678f230dd858bb80b94ffa76e4a3c"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d803aed036928d17520027277893cf7084fc2bc4927a3fba94d8f742b7faa507"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "125b7927722ac5131be444b196c24674f8da144a"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "e35f0f6dcd69db64eb03ac98b0edad3e213ed4176e052f24222103ded08e908b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ed83f07ad74603a7593bd868fc3e61b1c348730e"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "144512f74a128bf7f89691e9be490994992345be62b647949611f17bc86f9516"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9f8146175be3fa879136e02b8c9fffb7b4ef231c"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d8dff074664fab31893d3ecd2fe7d155797882951867ead8200328597882841e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5de3c4080c96f070b75790bf418f9c0771261932"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "5df6d52177059d8d9a3fc5031a7a7087fa5c2b976e37e0ff2748e844dc3f962d"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2debf643016f66feba8db93f59ebd595e23d5881"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "3d1e4ba90a73027a6cb763beaa99b0721bdc712ddff05a33c70aca147804379c"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "98942634e07c146191fac2febb48e337febcd7f7"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "835d542cbe951aae740e0c8cc9fcb2baeea06bb967a8565e3f2b18e8238bab59"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "321706ba1006c0c9851a1b7e92fa9cc9bf2e0417"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "cb82086fc295be16c706801b53d48ddbd9e40d7fecf00cdb13f3da838e2647d2"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "3370909bff2e2263fdccdb8deea9ffac86a4b32a"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "924588fb8a5e893b13d1e922fd511f8b3092a5b0505257b0751e0ed6c63a21f7"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "e51b079cad0dafbc3133c253396f58f7a523b124"
os = "macos"

    [[Netpbm.download]]
    sha256 = "97e8902d33b96bbfe9b1ad492dc3e844846869ed5a0435464fa60deaaa8b0b1b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "e9b8ddc7f69d419e70375af3faf87c2649e43d1c"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "af0c0245027f047fd43a4b7b415aeb3913ad1b54a9a8cd59d0426bb6848c921b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "ba96db27443a227b8a8d81386fe28d0f4119276e"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "a88954b7ef6223453bd40a5835218fb16c5d0541c88190324270f8f0a698cdb6"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "2b23b65beb31ac3cda558299d2389d6051f71235"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "4e15660efe0eeb2960c3fbcfcf158cace187a9689322f2fb7f6f9d8991a6f5ca"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.42+0/Netpbm.v10.86.42.x86_64-unknown-freebsd.tar.gz"
