[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "c1f5ba5770de187a743edb7ec5007a5ba245a933"
os = "macos"

    [[Netpbm.download]]
    sha256 = "d60f9752b3ae84525c76616b7ded618de2cba6dd6974a7c12a46093be2e647a9"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "985dee9ecd3a3b040fd1b31aa9faa61f9ac3524f"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "4cd55f8177ec2b1feae34ea94c7d3a5aae5e6204cc0285ae94efcce8563e7e23"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "3ca583f19e8dabf420a71ea3112bc68c1335cef1"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "00aba3fe59f3f1bf657fb2121629a7c4df4c60e176237bf5b13f2c7c2411b02b"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "b30e65413d3179945fb339aeb2d99958103839e1"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "17768f5aee12db678fdfcb9dc873e64a23794761e5dd28a757ddbbfe5bd7084c"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.aarch64-unknown-freebsd.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3be3c39779d73c4596a9b8eee06b012951386dcb"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "a87b254a52e2fb333f47da909d90353f4e66e29272bbdf224220b4ce76e0f947"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "70c1c6f672fb3d23c4baff18b705f651d7950fd7"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "df751dceb3b92a6ba9c638362d5d23274621fa8c63c7037aa654e68a3f95c633"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6770c2743ba3dc0b2b1d90b1d5e0739d2cdc00a7"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "9946400645b54eccd16ecfe2f42746d00867b514b33c7fed9ef24b378c959c2e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "565bc054bd1231fa8bc4f729726c893174305797"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "1937849da799308625d055dc3eda8e7a577faf9694e1696251d7323d49a339cc"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "3b3d62b95eafabb62ee0636339946107a0cf9096"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "cd6393bca1780f4b200d20669c8e8dc763b45b1517decd2ed9bb7f3f8bbd76f0"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "b3d4095ff3599ec2d09e347846b00e95b7eeef35"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "ea6478556fadbe441cd2a66f572d49223a91e66605c46e27fa0b691cc4a92ac6"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "6adc31c5b86c9614c20c67f66d82a3f362842237"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "2ded0a5cf3787e74a18ff846e51e7cb1ca7fb881d377619c19fb7f3dbefb5fc1"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "riscv64"
git-tree-sha1 = "ea4793064424778f04c9b31d06bd9f3160cc11bf"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "e52c753f7cc434fa5d51f017a5b7809e6eadfed8465d7e6735b3372b153572c2"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.riscv64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "030065f2fc5eda471ce5cacb42519cbe5769082a"
os = "macos"

    [[Netpbm.download]]
    sha256 = "830a6625fb66a62910027c98697b9688689a1bd432465c7be8727a8a425195cf"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "4969627ca586a9e65b24cd83dad6a8f01d925b9a"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "33224eb84fbb8c1e687f5ebca10c3490d3185bc00783231c0454c072580febc7"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "c6b29730a91ea6f43ec8afb66c7e24c491d8a98c"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "6153a4bdd61546dc09b4338db48e69feafbcad443e5e201e3510b3c2f4fc9906"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "28282c8d2d81fddada5984deb32f1513fb49b613"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "ab18c6cf14b72411af4864bfd9edc8fc6f3c821603f68113968ba088e7226276"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.50+0/Netpbm.v10.86.50.x86_64-unknown-freebsd.tar.gz"
