[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "5056702970af28cc4b924acf7b6472edb81d3dad"
os = "macos"

    [[Netpbm.download]]
    sha256 = "32dc610871707f3412ba091a0e18b0f0a4441973fdc980edb023fba1c0f2121a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "774e5e51211159fdf8ed6ab594c7ea0643b2e977"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "6f63888ac6b92527231d3340519c44f8167604c70862d31ada9f0647aa3f4404"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "f5e92db6cd01cb77bf22d99577bba6f48e7bb7d4"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "cdc4506e2de83d36d0d4891560df887ae6dd557a71c3fe094a15a09271a9b607"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "a954e048c5048c849c8c5d8394d5232c4f6d6294"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "7a151ce9226e152680aa809b77ad676c554d1d21f927d9519e6a5d61afa32371"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.aarch64-unknown-freebsd.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a497cf0709d0257c4a83cf5911e17514e16837c5"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "051f9e2dd9d87be96d1e3e57fcdecb56e5922314f37ca1b1130879392b3b7dce"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7502b24bab36c2a49c5e1939aa842814d04790ef"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "c1a24565b5f9111afeded82dd4efef3d259fd938fa16eee8b7c6fa0d3a05463a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "30ac0a44f985c6fecccd1a45ddfbdab6ff73fc9a"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "9eab17978c8ac40ddbdb52843ba185fb78bed7aca87ba78ef5904de9ac45c136"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3eef3a008b61c848a3a030744a8e8d09cb22176c"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "41620a8079df2d9a42ba48571f40c3e33234e6cef3b2aa03c2524937e86591a4"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "bac03075c985ef6962e12b77b0349caa15faac0d"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d293b4de4a1f320997d5b8aeb8a8e72350863059d84c40e8ad5ca7d814613618"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "806e9e9f42b63d11207b280c0cf5f53c03d16034"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "86271482d09cd05f255d03be302b6d96c279b194ecd62d491010a236937905e3"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "f9b251dd9e406dd300d4aa4c84d17380fa393ff2"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "33dcb1fa927ed44727c953cf8ccfbce30b300f69be85f6cb43026f68c51b5761"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "riscv64"
git-tree-sha1 = "4e9646accee11a4f3db6ad7b2b895b1ed2e5f0a5"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "42403ae7d364518060f0a6b7a12d88b7afd3c72c3a82254b381ac94d7d55645f"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.riscv64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "e15c7399e3b97eefebd224d38e6f9066dd0d2744"
os = "macos"

    [[Netpbm.download]]
    sha256 = "f1c80444747bcbe51b5fd873fc9ef494ee7bfcadec33c414a9407098190c5ca5"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "2b3972773ba8b016714b980beaccb90978b94207"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "a40b461b81dfcdb899a158dafd3ee816a56d480540e10418d89803700a53e626"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "f5d0a22b443cca228135f586bc7880fd3965d2ff"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "63de254f4f72d050aec6bc328bcc4d3ae9f1691660d58737a6d4eb7558a5cc44"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "2d4ef82a2b61234e8ca2442aad4f93ca94045381"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "cad1be3ba69fe2984aeda0e16d9f68199cc4b98e8bfec79c940b41603d507431"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.45+0/Netpbm.v10.86.45.x86_64-unknown-freebsd.tar.gz"
