[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "1df09e4bd47193c0a1f7cc557a1bd1008da3d1fe"
os = "macos"

    [[Netpbm.download]]
    sha256 = "31d0fd3b28be69dbfb533f7cd76d4db67b0c11ae5ecf7839eb0122e5174b733c"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.aarch64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "76a4e8a9a960a179061685e53a13cff792f16429"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "062f0c63100f1ca2b8665b743201359a270ea126f6cfaf56073db4f329f06508"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.aarch64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "ab66689a24621dbb68067ce3dbd3f69bcfaefd28"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "46d45ea0d2380e84443097b1d33db6907b6ac7f2d0455986daefff04fdb9b3b0"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.aarch64-linux-musl.tar.gz"
[[Netpbm]]
arch = "aarch64"
git-tree-sha1 = "d730b8403996f297be0795d052b22cd2a8c60760"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "42471739600e1b076978140a39e0112fd487954bf891160f84db4fa27eb06b55"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.aarch64-unknown-freebsd.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a8beddbbfcb4620455f91d4651f5ae6c0f58f505"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "755011531feb0b8dcc5d85f1343712a57ea23a6e2b6e66043253b8320464c70d"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.armv6l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "625274818644adfac7a4174f7309e37c25183ce1"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "dc428efa6d4f9e10a1e5481e5274c08d99f3e3319009c6a070b5c62c28d24eee"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.armv6l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a1364ff300c9e65883d6de4fcf1f3effa8eabc0a"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d1469f591c719457ce190dd45e5b3f8d0b47e3fbc995fbda9b302a4fd19b81d2"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.armv7l-linux-gnueabihf.tar.gz"
[[Netpbm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c424aca54d78f603134ab110b563f7e0aa5bf408"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "cd30ced8f6686319979f59b2048a48df9697b36fd00a3eaca3615a30f2ad5751"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.armv7l-linux-musleabihf.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "c3a4f4fa15b56b84d32437657bf30c96f1d0763c"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "98a21b9b17ae79d9587e6d5096eccfaea8c9ef087bc4e42538dc6bcbde3782b8"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.i686-linux-gnu.tar.gz"
[[Netpbm]]
arch = "i686"
git-tree-sha1 = "482e6df189c1ee223d4cd844bae85eaad4859cbf"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "a072da0ed24f24c34b87bbacafdcf2b14cc6563001393d7a9b867bfac0878007"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.i686-linux-musl.tar.gz"
[[Netpbm]]
arch = "powerpc64le"
git-tree-sha1 = "e87c36f08068ebea476a5d2077dce442f5a3f426"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "df21d549c30d75eeabca720570237a1ab6c8b1eca8207e2536726d61b45bc294"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.powerpc64le-linux-gnu.tar.gz"
[[Netpbm]]
arch = "riscv64"
git-tree-sha1 = "abaaeacbcd2651c9991f54fbdcc22da35080677f"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "5abfefc49eb36e32e1ad79f0a5e53e663ed7e86d081ea4425c8f46fe621f3b19"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.riscv64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "3223406186be823e14519051203111c0ded54bbd"
os = "macos"

    [[Netpbm.download]]
    sha256 = "add239d44764ca6036e78f4a4efbf7f33508e21d23982f16bd4dd2e1908f918e"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.x86_64-apple-darwin.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "5350678e3680839db57a5d10fd6d82a71c891623"
libc = "glibc"
os = "linux"

    [[Netpbm.download]]
    sha256 = "d33b181a04b93a6de054eb524de3462303ad805c84c167ff0b8ff7786cee9d9a"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.x86_64-linux-gnu.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "8357cefce9053d4bfe104e3e9fc28dac31e5d066"
libc = "musl"
os = "linux"

    [[Netpbm.download]]
    sha256 = "4d9f75563cdd5f314c640205f58b3e43e01a7e6406f8ff1d84a6a0ea1d2f7a26"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.x86_64-linux-musl.tar.gz"
[[Netpbm]]
arch = "x86_64"
git-tree-sha1 = "040f7abf311fd13b6a3ae5e2e196abd863e2d328"
os = "freebsd"

    [[Netpbm.download]]
    sha256 = "cc0877484559f5abcb06cc9d60d210b6c13d57d824835d163e2ffa4c16dcc0f7"
    url = "https://github.com/JuliaBinaryWrappers/Netpbm_jll.jl/releases/download/Netpbm-v10.86.44+0/Netpbm.v10.86.44.x86_64-unknown-freebsd.tar.gz"
